import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Users, Headphones, Wifi } from "lucide-react";
import { friends } from "@/data/mockData";
const SocialSidebar = () => {
    return (_jsxs(motion.aside, { initial: { x: 20, opacity: 0 }, animate: { x: 0, opacity: 1 }, transition: { duration: 0.4, delay: 0.1, ease: [0.22, 1, 0.36, 1] }, className: "hidden xl:flex fixed right-0 top-0 bottom-24 w-[280px] z-30 flex-col overflow-hidden", style: {
            background: "rgba(11,15,20,0.95)",
            borderLeft: "1px solid rgba(255,255,255,0.05)",
        }, children: [_jsxs("div", { className: "flex items-center gap-2.5 px-5 pt-20 pb-4 flex-shrink-0", children: [_jsx("div", { className: "w-7 h-7 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center", children: _jsx(Users, { className: "w-3.5 h-3.5 text-primary" }) }), _jsx("span", { className: "text-sm font-semibold text-white/80", children: "Listening with Friends" }), _jsxs("div", { className: "ml-auto flex items-center gap-1", children: [_jsx("div", { className: "w-1.5 h-1.5 rounded-full bg-accent animate-pulse" }), _jsxs("span", { className: "text-xs text-white/30 font-mono", children: [friends.filter((f) => f.isOnline).length, " live"] })] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto scrollbar-hide px-4 pb-4 space-y-2", children: [friends.map((friend, i) => (_jsx(motion.div, { initial: { opacity: 0, x: 12 }, animate: { opacity: 1, x: 0 }, transition: { delay: i * 0.07 + 0.3 }, className: `rounded-2xl p-3 transition-all duration-300 cursor-pointer group ${friend.isOnline
                            ? "hover:bg-white/5 border border-transparent hover:border-white/5"
                            : "opacity-40"}`, children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("div", { className: "relative flex-shrink-0", children: [_jsx("img", { src: friend.avatar, alt: friend.name, className: "w-9 h-9 rounded-full object-cover" }), _jsx("div", { className: `absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full border-2 border-obsidian ${friend.isOnline ? "bg-accent" : "bg-white/20"} ${friend.isOnline ? "status-pulse" : ""}` })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("p", { className: "text-xs font-semibold text-white/80 truncate", children: friend.name }), friend.isSynced && (_jsxs("div", { className: "flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-accent/10 border border-accent/20", children: [_jsx(Wifi, { className: "w-2.5 h-2.5 text-accent" }), _jsx("span", { className: "text-[10px] text-accent font-medium", children: "Synced" })] }))] }), friend.isOnline && (_jsxs("div", { className: "flex items-center gap-1 mt-0.5", children: [_jsx(Headphones, { className: "w-2.5 h-2.5 text-white/25" }), _jsxs("p", { className: "text-[11px] text-white/35 truncate", children: [friend.song, " \u00B7 ", friend.artist] })] }))] }), friend.isOnline && !friend.isSynced && (_jsx("button", { className: "opacity-0 group-hover:opacity-100 text-[10px] px-2 py-1 rounded-lg bg-primary/10 text-primary border border-primary/20 transition-all hover:bg-primary/20 flex-shrink-0", children: "Join" }))] }) }, friend.id))), _jsxs("div", { className: "mt-4 rounded-2xl p-4", style: {
                            background: "rgba(0,229,255,0.03)",
                            border: "1px solid rgba(0,229,255,0.08)",
                        }, children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx("div", { className: "w-1.5 h-1.5 rounded-full bg-primary animate-pulse" }), _jsx("span", { className: "text-xs text-primary/70 font-semibold", children: "Global Stream" })] }), _jsxs("p", { className: "text-xs text-white/40 leading-relaxed", children: ["Synced with", " ", _jsx("span", { className: "text-white/70 font-mono", children: "12,402" }), " listeners", _jsx("br", {}), _jsx("span", { className: "text-white/25", children: "across 84 countries" })] })] }), _jsxs("div", { className: "mt-2", children: [_jsx("p", { className: "text-white/25 text-xs font-semibold tracking-widest uppercase px-1 mb-2", children: "Activity" }), [
                                { name: "Alex", action: "added to playlist", item: "Neon Labyrinth", time: "2m ago" },
                                { name: "Mia", action: "liked", item: "Electric Cathedral", time: "8m ago" },
                                { name: "Jordan", action: "started session", item: "Synthwave Drive", time: "15m ago" },
                            ].map((act, i) => (_jsxs("div", { className: "flex items-start gap-2 py-2", children: [_jsx("div", { className: "w-1 h-1 rounded-full bg-primary/40 mt-2 flex-shrink-0" }), _jsxs("p", { className: "text-[11px] text-white/35 leading-relaxed", children: [_jsx("span", { className: "text-white/60", children: act.name }), " ", act.action, " ", _jsxs("span", { className: "text-primary/60", children: ["\"", act.item, "\""] })] }), _jsx("span", { className: "text-[10px] text-white/20 font-mono ml-auto flex-shrink-0", children: act.time })] }, i)))] })] })] }));
};
export default SocialSidebar;
