import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Play, Heart } from "lucide-react";
import { useState } from "react";
import Equalizer from "./Equalizer";
const SongCard = ({ song, isPlaying = false, onPlay, variant = "card", index }) => {
    const [liked, setLiked] = useState(song.liked);
    const [hovered, setHovered] = useState(false);
    if (variant === "row") {
        return (_jsxs(motion.div, { initial: { opacity: 0, x: -8 }, animate: { opacity: 1, x: 0 }, transition: { delay: (index || 0) * 0.05 }, className: `flex items-center gap-4 px-4 py-3 rounded-xl cursor-pointer group transition-all duration-300 ${isPlaying
                ? "bg-primary/5 border border-primary/20"
                : "hover:bg-white/5"}`, onClick: () => onPlay?.(song), children: [_jsxs("div", { className: "w-6 flex-shrink-0 text-center", children: [isPlaying ? (_jsx(Equalizer, { isPlaying: true, size: "sm" })) : (_jsx("span", { className: "text-white/40 text-sm font-mono group-hover:hidden", children: String(index + 1).padStart(2, "0") })), !isPlaying && (_jsx(Play, { className: "w-3.5 h-3.5 text-primary hidden group-hover:block mx-auto", fill: "currentColor" }))] }), _jsx("img", { src: song.cover, alt: song.title, className: "w-10 h-10 rounded-lg object-cover flex-shrink-0" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: `text-sm font-medium truncate ${isPlaying ? "text-primary" : "text-white/90"}`, children: song.title }), _jsx("p", { className: "text-xs text-white/40 truncate", children: song.artist })] }), _jsx("p", { className: "text-xs text-white/30 truncate hidden md:block w-32", children: song.album }), _jsx("p", { className: "text-xs text-white/30 font-mono w-12 text-right hidden lg:block", children: song.plays }), _jsxs("div", { className: "flex items-center gap-2 flex-shrink-0", children: [_jsx("button", { onClick: (e) => { e.stopPropagation(); setLiked(!liked); }, className: `transition-all duration-200 ${liked ? "text-accent" : "text-white/20 hover:text-white/60"}`, children: _jsx(Heart, { className: "w-4 h-4", fill: liked ? "currentColor" : "none" }) }), _jsx("span", { className: "text-white/30 text-xs font-mono", children: song.duration })] })] }));
    }
    return (_jsx(motion.div, { initial: { opacity: 0, y: 16 }, animate: { opacity: 1, y: 0 }, transition: { delay: (index || 0) * 0.06, type: "spring", stiffness: 300, damping: 30 }, whileHover: { scale: 1.03 }, whileTap: { scale: 0.98 }, onHoverStart: () => setHovered(true), onHoverEnd: () => setHovered(false), onClick: () => onPlay?.(song), className: "group cursor-pointer", children: _jsxs("div", { className: "glass-card rounded-2xl overflow-hidden transition-all duration-400", style: {
                boxShadow: hovered
                    ? "0 0 25px rgba(0,229,255,0.15), inset 0 1px 1px rgba(255,255,255,0.05)"
                    : "inset 0 1px 1px rgba(255,255,255,0.05), 0 10px 30px -10px rgba(0,0,0,0.5)",
            }, children: [_jsxs("div", { className: "relative aspect-square overflow-hidden", children: [_jsx("img", { src: song.cover, alt: song.title, className: "w-full h-full object-cover transition-transform duration-700 group-hover:scale-110" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" }), _jsx(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: hovered ? 1 : 0, scale: hovered ? 1 : 0.8 }, transition: { duration: 0.2 }, className: "absolute inset-0 flex items-center justify-center", children: _jsx("div", { className: "w-12 h-12 rounded-full bg-primary/20 backdrop-blur-sm border border-primary/40 flex items-center justify-center shadow-glow-cyan", children: isPlaying ? (_jsx(Equalizer, { isPlaying: true, size: "sm" })) : (_jsx(Play, { className: "w-5 h-5 text-primary ml-0.5", fill: "currentColor" })) }) }), _jsx("button", { onClick: (e) => { e.stopPropagation(); setLiked(!liked); }, className: "absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-all duration-200", children: _jsx(Heart, { className: `w-4 h-4 transition-colors ${liked ? "text-accent" : "text-white/70"}`, fill: liked ? "currentColor" : "none" }) })] }), _jsxs("div", { className: "p-3", children: [_jsx("p", { className: "text-sm font-semibold text-white/90 truncate", children: song.title }), _jsx("p", { className: "text-xs text-white/40 truncate mt-0.5", children: song.artist }), _jsxs("div", { className: "flex items-center justify-between mt-2", children: [_jsxs("span", { className: "text-xs text-white/25 font-mono", children: [song.plays, " plays"] }), _jsx("span", { className: "text-xs text-white/25 font-mono", children: song.duration })] })] })] }) }));
};
export default SongCard;
