import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Play, Sparkles, Radio } from "lucide-react";
import SongCard from "@/components/music/SongCard";
import PlaylistCard from "@/components/music/PlaylistCard";
import { trendingSongs, newReleases, playlists, genres, recentlyPlayed } from "@/data/mockData";
const SectionHeader = ({ title, subtitle }) => (_jsxs("div", { className: "flex items-end justify-between mb-5", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-bold text-white/90 tracking-tight", children: title }), subtitle && _jsx("p", { className: "text-xs text-white/35 mt-0.5", children: subtitle })] }), _jsx("button", { className: "text-xs text-primary/70 hover:text-primary transition-colors font-medium", children: "See all \u2192" })] }));
const HomeView = ({ currentSong, onPlay }) => {
    return (_jsxs("div", { className: "space-y-10 animate-fade-in", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, ease: [0.22, 1, 0.36, 1] }, className: "relative rounded-3xl overflow-hidden", style: {
                    height: "220px",
                    background: "linear-gradient(135deg, rgba(0,229,255,0.12) 0%, rgba(11,15,20,0.9) 60%, rgba(29,185,84,0.08) 100%)",
                    border: "1px solid rgba(0,229,255,0.12)",
                    boxShadow: "0 0 40px rgba(0,229,255,0.06), inset 0 1px 1px rgba(255,255,255,0.05)",
                }, children: [_jsxs("div", { className: "absolute inset-0 overflow-hidden", children: [_jsx("img", { src: "https://images.unsplash.com/photo-1614149162883-504ce4d13909?w=900&h=400&fit=crop", alt: "Featured", className: "w-full h-full object-cover opacity-20" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-[#0B0F14]/90 via-[#0B0F14]/50 to-transparent" })] }), _jsxs("div", { className: "relative z-10 flex flex-col justify-end h-full p-8", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Sparkles, { className: "w-3.5 h-3.5 text-primary" }), _jsx("span", { className: "text-xs text-primary/80 font-semibold tracking-widest uppercase", children: "Featured Now" })] }), _jsx("h1", { className: "text-3xl font-bold text-white tracking-tight-display text-balance mb-1", children: "Lost in the frequency." }), _jsx("p", { className: "text-sm text-white/40 mb-5", children: "Your personalized synthwave journey starts here." }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs(motion.button, { whileHover: { scale: 1.03 }, whileTap: { scale: 0.97 }, onClick: () => onPlay(trendingSongs[0]), className: "flex items-center gap-2 px-5 py-2.5 rounded-xl font-semibold text-sm transition-all", style: {
                                            background: "linear-gradient(135deg, #00E5FF, #00B8D4)",
                                            color: "#0B0F14",
                                            boxShadow: "0 0 20px rgba(0,229,255,0.3)",
                                        }, children: [_jsx(Play, { className: "w-4 h-4", fill: "currentColor" }), "Play Now"] }), _jsx("button", { className: "px-5 py-2.5 rounded-xl text-sm font-medium transition-all", style: { background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", color: "rgba(255,255,255,0.7)" }, children: "Explore" })] })] })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "Recently Played", subtitle: "Pick up where you left off" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-4 gap-4", children: recentlyPlayed.map((song, i) => (_jsx(SongCard, { song: song, isPlaying: currentSong?.id === song.id, onPlay: onPlay, index: i }, song.id))) })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "Trending Now", subtitle: "What the world is listening to" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4", children: trendingSongs.map((song, i) => (_jsx(SongCard, { song: song, isPlaying: currentSong?.id === song.id, onPlay: onPlay, index: i }, song.id))) })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "Browse by Genre" }), _jsx("div", { className: "grid grid-cols-3 lg:grid-cols-6 gap-3", children: genres.map((genre, i) => (_jsxs(motion.button, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: i * 0.05 }, whileHover: { scale: 1.04 }, whileTap: { scale: 0.97 }, className: "rounded-2xl p-4 text-left relative overflow-hidden group", style: {
                                background: `linear-gradient(135deg, ${genre.color}18, rgba(18,24,33,0.9))`,
                                border: `1px solid ${genre.color}28`,
                            }, children: [_jsx("div", { className: "absolute -top-3 -right-3 w-16 h-16 rounded-full opacity-10 group-hover:opacity-20 transition-opacity duration-300", style: { background: genre.color } }), _jsx("p", { className: "text-sm font-bold text-white/90 relative z-10", children: genre.name }), _jsx("p", { className: "text-[10px] font-mono text-white/30 mt-1 relative z-10", children: genre.count })] }, genre.name))) })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "New Releases", subtitle: "Fresh drops this week" }), _jsx("div", { className: "space-y-1", children: newReleases.map((song, i) => (_jsx(SongCard, { song: song, variant: "row", isPlaying: currentSong?.id === song.id, onPlay: onPlay, index: i }, song.id))) })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "Your Playlists", subtitle: "Curated for your sessions" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-4 gap-4", children: playlists.map((pl, i) => (_jsx(PlaylistCard, { playlist: pl, index: i }, pl.id))) })] }), _jsxs("section", { children: [_jsx(SectionHeader, { title: "Radio & Moods", subtitle: "Stations powered by your taste" }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: [
                            { name: "Synthwave Station", listeners: "3,201 listening", color: "#00E5FF", cover: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop" },
                            { name: "Late Night Vibes", listeners: "1,840 listening", color: "#7C3AED", cover: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&h=300&fit=crop" },
                            { name: "Focus Flow", listeners: "5,610 listening", color: "#1DB954", cover: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=300&h=300&fit=crop" },
                            { name: "Cyberpunk Radio", listeners: "2,093 listening", color: "#F59E0B", cover: "https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=300&h=300&fit=crop" },
                        ].map((station, i) => (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: i * 0.06 }, whileHover: { scale: 1.02 }, className: "flex items-center gap-4 p-4 rounded-2xl cursor-pointer group transition-all", style: {
                                background: "rgba(18,24,33,0.7)",
                                border: "1px solid rgba(255,255,255,0.05)",
                            }, children: [_jsxs("div", { className: "relative flex-shrink-0", children: [_jsx("img", { src: station.cover, alt: station.name, className: "w-14 h-14 rounded-xl object-cover" }), _jsx("div", { className: "absolute inset-0 rounded-xl opacity-0 group-hover:opacity-100 transition-all flex items-center justify-center", style: { background: "rgba(0,0,0,0.4)" }, children: _jsx(Radio, { className: "w-5 h-5", style: { color: station.color } }) })] }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-semibold text-white/90 truncate", children: station.name }), _jsxs("div", { className: "flex items-center gap-1.5 mt-0.5", children: [_jsx("div", { className: "w-1.5 h-1.5 rounded-full animate-pulse", style: { background: station.color } }), _jsx("p", { className: "text-xs font-mono", style: { color: `${station.color}80` }, children: station.listeners })] })] })] }, station.name))) })] })] }));
};
export default HomeView;
