import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import { Search, Play, X } from "lucide-react";
import { trendingSongs, newReleases, genres } from "@/data/mockData";
import SongCard from "@/components/music/SongCard";
const allSongs = [...trendingSongs, ...newReleases];
const SearchView = ({ currentSong, onPlay }) => {
    const [query, setQuery] = useState("");
    const [filter, setFilter] = useState("all");
    const filteredSongs = allSongs.filter((s) => query.length === 0 ||
        s.title.toLowerCase().includes(query.toLowerCase()) ||
        s.artist.toLowerCase().includes(query.toLowerCase()) ||
        s.album.toLowerCase().includes(query.toLowerCase()));
    const uniqueArtists = [...new Set(allSongs.map((s) => s.artist))];
    const uniqueAlbums = [...new Set(allSongs.map((s) => s.album))];
    const hasQuery = query.length > 0;
    return (_jsxs("div", { className: "space-y-8 animate-fade-in", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white/90 tracking-tight-display mb-1", children: "Search" }), _jsx("p", { className: "text-sm text-white/35", children: "Discover music, artists, and albums" })] }), _jsx("div", { className: "relative", children: _jsxs("div", { className: "flex items-center gap-3 rounded-2xl px-5 py-3.5 transition-all duration-300 max-w-2xl", style: {
                        background: "rgba(255,255,255,0.05)",
                        border: "1px solid rgba(0,229,255,0.3)",
                        boxShadow: "0 0 16px rgba(0,229,255,0.1)",
                    }, children: [_jsx(Search, { className: "w-5 h-5 text-primary/60 flex-shrink-0" }), _jsx("input", { type: "text", autoFocus: true, placeholder: "What do you want to listen to?", value: query, onChange: (e) => setQuery(e.target.value), className: "flex-1 bg-transparent text-white/90 placeholder:text-white/25 text-sm outline-none" }), query && (_jsx("button", { onClick: () => setQuery(""), className: "text-white/30 hover:text-white/60 transition-colors", children: _jsx(X, { className: "w-4 h-4" }) }))] }) }), _jsx(AnimatePresence, { children: hasQuery && (_jsx(motion.div, { initial: { opacity: 0, y: -8 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -8 }, className: "flex gap-2", children: ["all", "songs", "artists", "albums"].map((f) => (_jsx("button", { onClick: () => setFilter(f), className: `px-4 py-1.5 rounded-full text-xs font-medium capitalize transition-all duration-200 ${filter === f
                            ? "bg-primary/15 text-primary border border-primary/30 shadow-glow-cyan"
                            : "text-white/40 border border-white/10 hover:border-white/20 hover:text-white/60"}`, children: f }, f))) })) }), _jsx(AnimatePresence, { mode: "wait", children: hasQuery ? (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, className: "space-y-8", children: [(filter === "all" || filter === "songs") && (_jsxs("section", { children: [_jsx("h2", { className: "text-sm font-semibold text-white/50 uppercase tracking-widest mb-4", children: "Songs" }), filteredSongs.length > 0 ? (_jsx("div", { className: "space-y-1", children: filteredSongs.map((song, i) => (_jsx(SongCard, { song: song, variant: "row", isPlaying: currentSong?.id === song.id, onPlay: onPlay, index: i }, song.id))) })) : (_jsxs("p", { className: "text-white/25 text-sm", children: ["No songs found for \"", query, "\""] }))] })), (filter === "all" || filter === "artists") && (_jsxs("section", { children: [_jsx("h2", { className: "text-sm font-semibold text-white/50 uppercase tracking-widest mb-4", children: "Artists" }), _jsx("div", { className: "grid grid-cols-3 sm:grid-cols-5 gap-4", children: uniqueArtists
                                        .filter((a) => !hasQuery || a.toLowerCase().includes(query.toLowerCase()))
                                        .map((artist, i) => {
                                        const song = allSongs.find((s) => s.artist === artist);
                                        return (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: i * 0.04 }, className: "flex flex-col items-center gap-2 p-3 rounded-2xl hover:bg-white/5 cursor-pointer transition-all group", children: [_jsxs("div", { className: "relative", children: [_jsx("img", { src: song.cover, alt: artist, className: "w-16 h-16 rounded-full object-cover border-2 border-white/10 group-hover:border-primary/30 transition-all" }), _jsx("div", { className: "absolute inset-0 rounded-full bg-primary/0 group-hover:bg-primary/10 transition-all flex items-center justify-center", children: _jsx(Play, { className: "w-5 h-5 text-primary opacity-0 group-hover:opacity-100 transition-opacity", fill: "currentColor" }) })] }), _jsx("p", { className: "text-xs font-medium text-white/80 text-center truncate w-full", children: artist }), _jsx("p", { className: "text-[10px] text-white/30 font-mono", children: "Artist" })] }, artist));
                                    }) })] })), (filter === "all" || filter === "albums") && (_jsxs("section", { children: [_jsx("h2", { className: "text-sm font-semibold text-white/50 uppercase tracking-widest mb-4", children: "Albums" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-4", children: uniqueAlbums
                                        .filter((a) => !hasQuery || a.toLowerCase().includes(query.toLowerCase()))
                                        .map((album, i) => {
                                        const song = allSongs.find((s) => s.album === album);
                                        return (_jsx(motion.div, { initial: { opacity: 0, y: 12 }, animate: { opacity: 1, y: 0 }, transition: { delay: i * 0.05 }, whileHover: { scale: 1.03 }, className: "cursor-pointer group", children: _jsxs("div", { className: "rounded-2xl overflow-hidden transition-all duration-300", style: {
                                                    background: "rgba(18,24,33,0.8)",
                                                    border: "1px solid rgba(255,255,255,0.05)",
                                                    boxShadow: "inset 0 1px 1px rgba(255,255,255,0.04)",
                                                }, children: [_jsxs("div", { className: "aspect-square overflow-hidden relative", children: [_jsx("img", { src: song.cover, alt: album, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" }), _jsx("div", { className: "absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center", children: _jsx("div", { className: "w-9 h-9 rounded-full bg-primary/20 border border-primary/40 flex items-center justify-center", children: _jsx(Play, { className: "w-4 h-4 text-primary ml-0.5", fill: "currentColor" }) }) })] }), _jsxs("div", { className: "p-2.5", children: [_jsx("p", { className: "text-xs font-semibold text-white/80 truncate", children: album }), _jsx("p", { className: "text-[10px] text-white/35 truncate mt-0.5", children: song.artist })] })] }) }, album));
                                    }) })] }))] }, "results")) : (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, className: "space-y-8", children: [_jsxs("section", { children: [_jsx("h2", { className: "text-sm font-semibold text-white/50 uppercase tracking-widest mb-5", children: "Browse Genres" }), _jsx("div", { className: "grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3", children: genres.map((genre, i) => (_jsxs(motion.button, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, transition: { delay: i * 0.05 }, whileHover: { scale: 1.04 }, whileTap: { scale: 0.97 }, className: "rounded-2xl p-5 text-left relative overflow-hidden group", style: {
                                            background: `linear-gradient(135deg, ${genre.color}20, rgba(18,24,33,0.9))`,
                                            border: `1px solid ${genre.color}30`,
                                        }, children: [_jsx("div", { className: "absolute -top-4 -right-4 w-20 h-20 rounded-full opacity-15 group-hover:opacity-30 transition-opacity duration-300", style: { background: genre.color } }), _jsx("p", { className: "text-sm font-bold text-white/90 relative z-10", children: genre.name }), _jsx("p", { className: "text-[10px] font-mono text-white/30 mt-1.5 relative z-10", children: genre.count })] }, genre.name))) })] }), _jsxs("section", { children: [_jsx("h2", { className: "text-sm font-semibold text-white/50 uppercase tracking-widest mb-4", children: "Top Charts" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-3", children: [
                                        { name: "Global Top 50", description: "Updated daily", color: "#00E5FF", cover: "https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=300&h=300&fit=crop" },
                                        { name: "Viral Hits", description: "Trending everywhere", color: "#1DB954", cover: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop" },
                                        { name: "New Music Friday", description: "Fresh every week", color: "#7C3AED", cover: "https://images.unsplash.com/photo-1484876065684-b1cf66c2a90e?w=300&h=300&fit=crop" },
                                        { name: "Decade Rewind", description: "Classic hits reborn", color: "#F59E0B", cover: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=300&h=300&fit=crop" },
                                    ].map((chart, i) => (_jsxs(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: i * 0.06 }, whileHover: { scale: 1.02 }, className: "flex items-center gap-4 p-4 rounded-2xl cursor-pointer group transition-all", style: {
                                            background: "rgba(18,24,33,0.7)",
                                            border: "1px solid rgba(255,255,255,0.05)",
                                        }, children: [_jsx("img", { src: chart.cover, alt: chart.name, className: "w-14 h-14 rounded-xl object-cover flex-shrink-0" }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-sm font-semibold text-white/90", children: chart.name }), _jsx("p", { className: "text-xs text-white/35 mt-0.5", children: chart.description })] }), _jsx("div", { className: "w-8 h-8 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-all", style: { background: `${chart.color}20`, border: `1px solid ${chart.color}40` }, children: _jsx(Play, { className: "w-3.5 h-3.5 ml-0.5", style: { color: chart.color }, fill: "currentColor" }) })] }, chart.name))) })] })] }, "browse")) })] }));
};
export default SearchView;
